<?php

/**
 * @file
 * This file demonstrates how to use hook functions.
 */

/**
 * Implements hook_form_alter().
 */
function mymodule_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  // \Drupal::messenger()->addMessage(t("Form id @id", ['@id' => $form_id]));
  if ($form_id == 'node_news_wilmer_edit_form') {
    $form['actions']['submit']['#value'] = t('Save this awesome article');
  }
}

/**
 * Implements hook_cron().
 */
function mymodule_cron() {
  \Drupal::messenger()->addMessage(t("Hello from mymodule cron hook :)"));
}


